services:
  - type: web
    name: xclsv-process-hub-api
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: https://web-xclsv.vercel.app,http://localhost:3000
